[package]
name = "validation"
version = "0.1.0"
authors = ["Joseph.Orme <joseph.orme@asurion.com>"]
edition = "2018"

[dependencies]
serde = "1.0.117"
serde_derive = "1.0.118"
serde_json = "1.0.60"

[dependencies.uuid]
version = "0.8.1"
features = ["v4", "serde"]
